import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Smart Travel App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "Smart Travel Planning Platform",
    template: "%s | Smart Travel Planning Platform",
  },

  description:
    "A modern travel planning platform built with Next.js, TypeScript, Tailwind CSS, Google Maps, and OpenWeather API.",

  keywords: [
    "Travel",
    "Next.js",
    "Google Maps",
    "Weather API",
    "Budget Planner",
    "Travel Dashboard",
  ],

  authors: [{ name: "Meghana G Janginavar" }],

  creator: "Meghana G Janginavar",

  applicationName: "Smart Travel Planning Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      {children}
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop
        closeOnClick
        pauseOnHover
        draggable
        theme="light"
      />
    </body>
    </html>
  );
}
